import "./globals.css";

import type { Metadata } from "next";
import { Open_Sans, Roboto_Mono } from "next/font/google";

const openSans = Open_Sans({
  weight: "variable",
  variable: "--font-open-sans",
  display: "swap",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  weight: "variable",
  variable: "--font-roboto-mono",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable} ${robotoMono.variable}`}>
      <body>
        <div
          className={`relative grid min-h-screen grid-rows-[1fr_auto] antialiased`}
        >
          <header className="absolute inset-x-0 top-0 grid place-items-center border-2 border-dotted bg-green-300 py-8">
            <p>Header</p>
          </header>
          <main className="place-items-center border-2 border-dotted bg-pink-300 pb-8 pt-28">
            {children}
            <pre>This is some text in mono</pre>
          </main>
          <footer className="grid place-items-center bg-blue-300 py-8">
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
