import "./globals.css";

import type { Metadata } from "next";
import { Open_Sans, Roboto_Mono } from "next/font/google";

const openSans = Open_Sans({
  weight: "variable",
  variable: "--font-open-sans",
  display: "swap",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  weight: "variable",
  variable: "--font-roboto-mono",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable} ${robotoMono.variable}`}>
      <body>
        <div
          className={`relative antialiased min-h-screen grid grid-rows-[1fr_auto]`}
        >
          <header className="grid place-items-center py-8 border-dotted border-2 bg-green-300 absolute inset-x-0 top-0">
            <p>Header</p>
          </header>
          <main className="border-dotted border-2 place-items-center pt-28 pb-8 bg-pink-300">
            {children}
            <pre>This is some text in mono</pre>
          </main>
          <footer className="grid place-items-center py-8 bg-blue-300">
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
